// All characters share the same HP and speed — only weapon differs.
const BASE_HEALTH = 100;
const BASE_SPEED  = 8;

export const CLASSES = [
  {
    id:           'emperor',
    friendName:   'GALACTIC EMPEROR',
    title:        'The Emperor',
    emoji:        '👑',
    bodyColor:    0xaa33ff,
    crosshairId:  'minigun',
    health:       BASE_HEALTH,
    speed:        BASE_SPEED,
    damage:       28,
    fireRate:     110,
    recoil:       0.04,
    weapon:       'MINIGUN',
    pellets:      1,
    spread:       0.055,
    ammo:         100,
    reloadTime:   3000,
    desc:         'Rules the battlefield from up close'
  },
  {
    id:           'joab',
    friendName:   'JOAB',
    title:        'The Warrior',
    emoji:        '⚔️',
    bodyColor:    0x2244cc,
    crosshairId:  'minigun',
    health:       BASE_HEALTH,
    speed:        BASE_SPEED,
    damage:       22,
    fireRate:     110,
    recoil:       0.025,
    weapon:       'DUAL M4',
    pellets:      1,
    spread:       0.05,
    ammo:         50,
    reloadTime:   2400,
    desc:         'Two M4s, double the trouble'
  },
  {
    id:           'snake',
    friendName:   'SNAKE',
    title:        'The Shadow',
    emoji:        '🐍',
    bodyColor:    0x22aa44,
    crosshairId:  'smg',
    health:       BASE_HEALTH,
    speed:        BASE_SPEED,
    damage:       18,
    fireRate:     110,
    recoil:       0.014,
    weapon:       'AK-47',
    pellets:      1,
    spread:       0.05,
    ammo:         30,
    reloadTime:   2200,
    desc:         'Slithers through the chaos'
  },
  {
    id:           'sofa',
    friendName:   'SOFA',
    title:        'The Wildcard',
    emoji:        '🛋️',
    bodyColor:    0xff7700,
    crosshairId:  'shotgun',
    health:       BASE_HEALTH,
    speed:        BASE_SPEED,
    damage:       18,
    fireRate:     700,
    recoil:       0.065,
    weapon:       'SHOTGUN',
    pellets:      8,
    spread:       0.16,
    ammo:         8,
    reloadTime:   2500,
    desc:         'Why aim? Just spray and pray'
  },
  {
    id:           'advisor',
    friendName:   'ADVISOR',
    title:        'The Strategist',
    emoji:        '🎩',
    bodyColor:    0x114488,
    crosshairId:  'sniper',
    health:       BASE_HEALTH,
    speed:        BASE_SPEED,
    damage:       45,
    fireRate:     550,
    recoil:       0.03,
    weapon:       'DMR',
    pellets:      1,
    spread:       0.006,
    ammo:         20,
    reloadTime:   2200,
    desc:         'Always three steps ahead'
  },
  {
    id:           'razi',
    friendName:   'CUTE RAZI',
    title:        'The Wild One',
    emoji:        '🌸',
    bodyColor:    0xff44aa,
    crosshairId:  'smg',
    health:       BASE_HEALTH,
    speed:        BASE_SPEED,
    damage:       14,
    fireRate:     90,
    recoil:       0.018,
    weapon:       'SMG',
    pellets:      1,
    spread:       0.04,
    ammo:         40,
    reloadTime:   1800,
    desc:         "Don't let the name fool you"
  },
];
