export const CLASSES = [
  {
    id: 'tank',
    friendName: 'AMIT',
    title: 'The Tank',
    emoji: '💪',
    bodyColor: 0xcc2222,
    health: 200,
    speed: 5,
    damage: 28,
    fireRate: 320,
    weapon: 'MINIGUN',
    pellets: 1,
    spread: 0.06,
    ammo: Infinity,
    desc: 'Slow but absolutely built different'
  },
  {
    id: 'sniper',
    friendName: 'YOSSI',
    title: 'The Sniper',
    emoji: '🎯',
    bodyColor: 0x2244cc,
    health: 80,
    speed: 6,
    damage: 95,
    fireRate: 1400,
    weapon: 'RIFLE',
    pellets: 1,
    spread: 0.004,
    ammo: Infinity,
    desc: 'One tap or go home'
  },
  {
    id: 'rusher',
    friendName: 'KOBI',
    title: 'The Rusher',
    emoji: '⚡',
    bodyColor: 0x22aa44,
    health: 90,
    speed: 13,
    damage: 10,
    fireRate: 90,
    weapon: 'SMG',
    pellets: 1,
    spread: 0.08,
    ammo: Infinity,
    desc: 'Runs faster than he thinks'
  },
  {
    id: 'shotgunner',
    friendName: 'MOSHE',
    title: 'The Wildcard',
    emoji: '💥',
    bodyColor: 0xff7700,
    health: 130,
    speed: 7,
    damage: 16,
    fireRate: 750,
    weapon: 'SHOTGUN',
    pellets: 7,
    spread: 0.18,
    ammo: Infinity,
    desc: "Why aim? Just spray and pray"
  }
];
